spring:
  application:
    name: networkassistant

  datasource:
    url: jdbc:postgresql://ep-wispy-haze-aibhbhdf.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_nFRUyVru1w7G

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

jwt:
  secret: YOUR_SECRET
  expiration: 86400000

file:
  upload-dir: uploads